spring:
  application:
    name: employees-api
    config:
      import: optional:aws-secretsmanager:employees/dynamodb/secret
      main:
        allow-bean-definition-overriding: true
aws:
  dynamodb:
    accessKey: ${DYNAMODB_ACCESS_KEY}
    secretKey: ${DYNAMODB_SECRET_KEY}
    endpoint: ${DYNAMODB_ENDPOINT}
    region: ${DYNAMODB_REGION}
